<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/composer/autoload_real.php';

    function my_autoload ($pClassName) {
        $pClassName = str_replace('\\', DIRECTORY_SEPARATOR, $pClassName);
        include(__DIR__ . "/src/" . $pClassName . ".php");
	}
    spl_autoload_register("my_autoload");

return ComposerAutoloaderInit1a321fa3d36f720dc2bdf3098da063e9::getLoader();
